swiftlang/swift-book

- Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
Those seem to be an artefact of importing the content?
> Remove `\ `

- Style.md
No content changes.
Fixes https://github.com/apple/swift-book/issues/15
> Discuss markdown headings in the style guide.

- Sources/TSPL/TSPL.docc/ReferenceManual/LexicalStructure.md
> Add "await" to the list of keywords.

- Sources/TSPL/TSPL.docc/LanguageGuide/OpaqueTypes.md
Replace this paragraph with your rationale and a brief summary of what changed.
Fixes https://github.com/apple/swift-book/issues/####
> Fixed typo smallTriange -> smallTriangle

- Sources/TSPL/TSPL.docc/TSPL.md
> Remove title heading and automatic see-also section

- Sources/TSPL/TSPL.docc/LanguageGuide/Generics.md
- Sources/TSPL/TSPL.docc/ReferenceManual/Attributes.md
- Sources/TSPL/TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md
- Sources/TSPL/TSPL.docc/ReferenceManual/Types.md
Change some places that got didn't get fixed by PR #60 and PR #50.
> Fix straggler comment syntax and blank lines

- Sources/TSPL/TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md
> Add missing headings and abstract to Summary of the Grammar

- Sources/TSPL/TSPL.docc/LanguageGuide/TypeCasting.md
> Correct the spelling/formatting of an initializer.

- Sources/TSPL/TSPL.docc/LanguageGuide/AutomaticReferenceCounting.md
- Sources/TSPL/TSPL.docc/LanguageGuide/Closures.md
- Sources/TSPL/TSPL.docc/LanguageGuide/CollectionTypes.md
- Sources/TSPL/TSPL.docc/LanguageGuide/ControlFlow.md
- Sources/TSPL/TSPL.docc/LanguageGuide/Inheritance.md
- Sources/TSPL/TSPL.docc/LanguageGuide/MemorySafety.md
- Sources/TSPL/TSPL.docc/LanguageGuide/Properties.md
- Sources/TSPL/TSPL.docc/LanguageGuide/StringsAndCharacters.md
- Sources/TSPL/TSPL.docc/LanguageGuide/TheBasics.md
- Sources/TSPL/TSPL.docc/ReferenceManual/Attributes.md
- Sources/TSPL/TSPL.docc/ReferenceManual/Declarations.md
- Sources/TSPL/TSPL.docc/ReferenceManual/Statements.md
> Restore paragraph breaks that were lost lost during the RST export

- Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md
> Add missing "prints" comment

- Sources/TSPL/TSPL.docc/LanguageGuide/Concurrency.md
This exporter issue was missed in https://github.com/apple/swift-book/pull/75.
> Restore a numbered list

- Style.md
Per discussion with Chuck; prompted by [SE-0376](https://github.com/apple/swift-evolution/blob/main/proposals/0376-function-back-deployment.md).
> Add a style entry for "back deploy".

- TSPL.docc/ReferenceManual/Declarations.md
Hi!
I'm reading this swift book and requesting PR because there are something wrong.
1. Spelling error
This mention is about actor not structure, so I modified spelling from structure type to actor type.
2. Spacing error
There are incorrect punctuation in that sentence.
> Spelling & spacing modify

- bin/preflight
> Add a script to perform pre-build checks.

- TSPL.docc/ReferenceManual/Attributes.md
- TSPL.docc/ReferenceManual/Statements.md
> Add visionOS to the platform lists

- TSPL.docc/LanguageGuide/AutomaticReferenceCounting.md
- TSPL.docc/LanguageGuide/ControlFlow.md
> Avoid 'neither nor'

- TSPL.docc/LanguageGuide/Macros.md
> Unflip two words in Macros chapter

- TSPL.docc/GuidedTour/GuidedTour.md
> Show concurrency in the guided tour

- TSPL.docc/ReferenceManual/Attributes.md
- TSPL.docc/ReferenceManual/Declarations.md
- TSPL.docc/ReferenceManual/Expressions.md
> Expand reference for macros.

- TSPL.docc/ReferenceManual/Attributes.md
Fixes: https://github.com/apple/swift-book/issues/202
Fixes: rdar://117591533
> Add reference for @backDeployed

- TSPL.docc/LanguageGuide/Closures.md
> Frame closures less in terms of Obj-C and C blocks

- TSPL.docc/ReferenceManual/LexicalStructure.md
Fixes: https://github.com/apple/swift-book/issues/230
> Add #unavailable to list of keywords

- TSPL.docc/ReferenceManual/Attributes.md
> Add reference for @preconcurrency 

- TSPL.docc/ReferenceManual/Attributes.md
> Add reference for noasync in @available [SE-0340]

- TSPL.docc/ReferenceManual/Attributes.md
> Remove outdated note about frozen

- TSPL.docc/ReferenceManual/Declarations.md
> Correct subscript setter name

- TSPL.docc/ReferenceManual/Statements.md
> Add WebAssembly to the list of architectures
