swiftlang/swift-book

README.md

Replaced link text in the Readme file with a working link for direct access to the swift docs website.

Fixed a hyperlink

---

Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md

Very small change
Fibonacci is a proper noun so give it a capital letter

Capitalize Fibonacci

---

Sources/TSPL/TSPL.docc/GuidedTour/Compatibility.md

Updated concurrency deployment target to reflect Xcode 13.2's support for concurrency back to the two earlier versions of the OSes.
Fixes #21.
To keep changes minimal, and keep the paragraph clean and concise, this purposefully doesn't add wording about Xcode 13 and 13.1 only supporting macOS 12 and up, and Xcode 13.2 adding the backwards compatibility, nor any of the history of how that support was added. If someone wants to add wording to that effect that should probably be discussed separately and elsewhere.

Changed concurrency version back to 5.5 from 5.7.

---

Sources/TSPL/TSPL.docc/GuidedTour/Compatibility.md

Per Apple Style Guide [entry](https://support.apple.com/guide/applestyleguide/v-apsg51b3c806/web) for "version number":
> When referring to a major release number (such as macOS 10.14 or iOS 12), omit any trailing .0 unless it’s needed for clarity.

Omit trailing "dot zero" in version number

---

Sources/TSPL/TSPL.docc/ReferenceManual/Statements.md

The claim is immediatly disproved on the grammer rule description below that states that the `while` condition is an expression. An expression in turn does not comprise an optional binding. The grammar rule seems to be correct since it matches with the bahavior of the Swift compiler and the SwiftSyntax library.

Remove claim on possible optional bindings in repeat-while conditions

---

Sources/TSPL/TSPL.docc/ReferenceManual/Statements.md

This patch adds an example of how the defer statement is lexically scoped and will execute at the end of the scope, not the end of a function.

Include example of defer lexical scoping

---

Sources/TSPL/TSPL.docc/LanguageGuide/TheBasics.md

I would argue that Swift is not *new* any more, it is a mature language at this point and the first sentence of `The Basics` of Swift ought to reflect that 🎓🎉

Swift graduates from school.

---

Sources/TSPL/TSPL.docc/LanguageGuide/Concurrency.md

Hello 👋🏻, while reading the [Defining and Calling Asynchronous Functions page](https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html#ID639), I noticed the syntax of `add` and `remove` method was wrong, because there was no comma. 
- Fix swift syntax by adding comma.
- Update code snippet to swift
Screenshot of content after changes:

Fix swift syntax in concurrency page

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

I based these templates of of what Swift and Swift-DocC use.
In the pull request template, I linked to the full docs for the Swift CI bot — but this repository only has some of its features enabled.  (For example, it doesn't support "test and merge".)  I'm not sure it's worth getting into that level of detail there.
Under the issues template, are there other links we should add?
For now, I'm leaving blank issues enabled to cover things that don't fall under either template, like adopting new features added to DocC or blockers for publication to Swift.org from this repository.
In the future, when we publish from this version, I'd expect us to add a specific template for updating the docs after a Swift Evolution proposal is accepted.
Instead of just reviewing the YAML version of in the …

Add templates for PRs and issues

---

Sources/TSPL/TSPL.docc/ReferenceManual/LexicalStructure.md

Exported from the RST version, where this old branch was reviewed by Steve Canon <scanon@apple.com> on Aug 30 and merged Oct 5.

Add inits and subscripts to the underscore rule.

---

.gitignore
Sources/TSPL/TSPL.docc/LanguageGuide/Closures.md
Sources/TSPL/TSPL.docc/LanguageGuide/CollectionTypes.md
Sources/TSPL/TSPL.docc/LanguageGuide/ControlFlow.md
Sources/TSPL/TSPL.docc/LanguageGuide/ErrorHandling.md
Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
Sources/TSPL/TSPL.docc/LanguageGuide/TheBasics.md
Sources/TSPL/TSPL.docc/ReferenceManual/Attributes.md
Sources/TSPL/TSPL.docc/ReferenceManual/Declarations.md
Sources/TSPL/TSPL.docc/ReferenceManual/Expressions.md
Sources/TSPL/TSPL.docc/ReferenceManual/GenericParametersAndArguments.md
Sources/TSPL/TSPL.docc/ReferenceManual/LexicalStructure.md
Sources/TSPL/TSPL.docc/ReferenceManual/Patterns.md
Sources/TSPL/TSPL.docc/ReferenceManual/Statements.md
Sources/TSPL/TSPL.docc/ReferenceManual/Types.md

- Update code snippet to Swift
Fix some Swift code snippet does not use `swift` metadata
> Actually there are other cases for this situation. Since they are incomplete Swift Code, should we mark the `swift` metadata to add syntax highlighting support?
Before (Without Swift Syntax highlighting)
After
- Update gitignore
Ignore the .docc-build folder after `docc preview TSPL.docc`

Mark "syntax outline" code listings as Swift

---

Sources/TSPL/TSPL.docc/ReferenceManual/AboutTheLanguageReference.md
Sources/TSPL/TSPL.docc/ReferenceManual/Attributes.md
Sources/TSPL/TSPL.docc/ReferenceManual/Declarations.md
Sources/TSPL/TSPL.docc/ReferenceManual/Expressions.md
Sources/TSPL/TSPL.docc/ReferenceManual/GenericParametersAndArguments.md
Sources/TSPL/TSPL.docc/ReferenceManual/LexicalStructure.md
Sources/TSPL/TSPL.docc/ReferenceManual/Patterns.md
Sources/TSPL/TSPL.docc/ReferenceManual/Statements.md
Sources/TSPL/TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md
Sources/TSPL/TSPL.docc/ReferenceManual/Types.md
Sources/TSPL/TSPL.docc/TSPL.md

DocC doesn't support subscripts, so instead of using subscript "opt" for optionality, use a postfix question mark.  Alternatives considered included text like "OPT" or "(opt)" and Unicode subscript characters.  The former are hard to read and interrupt the flow of the grammar.  The latter render poorly because they're intended for phonetic annotation, so the different letters don't share a baseline in many fonts.
It's a known issue that DocC doesn't support hard breaks, so insert a paragraph break between each grammar production for now.  I added a "double" paragraph break between groups, where there used to be a blank line, to preserve that information for when DocC adds hard break support in the future.
Fixes https://github.com/apple/swift-book/issues/3
Fixes rdar://101001280

Convert the formal grammar for DocC compatibility

---

Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md

These examples used to contrast the literal `[]` and initializer `[String]()` syntax, but we revised the book to remove the latter as part of a [style update](https://github.com/apple/swift-book/commit/639bcc61dde12b16cb50fcd81885292bfd6a2883).
Fixes rdar://101867425

Fix the tour's example for empty array & dictionary syntax

---

Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md
Sources/TSPL/TSPL.docc/LanguageGuide/AdvancedOperators.md
Sources/TSPL/TSPL.docc/LanguageGuide/ControlFlow.md
Sources/TSPL/TSPL.docc/LanguageGuide/Properties.md
Sources/TSPL/TSPL.docc/ReferenceManual/Expressions.md
bin/find_screenshot_changes

The iBooks Store was renamed several years ago — the comment markers should follow the current name.
When we're able to publish an ePUB version again (https://github.com/apple/swift-book/issues/2), we probably want to retake all of the screenshots.  We can update the value of `COMMIT` in the script at that time, to help us after that so we can find and retake only things that change.
Fixes rdar://101972172

Update name in screenshot markers

---

Sources/TSPL/TSPL.docc/LanguageGuide/Protocols.md

For example, this works even though the C class isn't marked @objc, isn't a subclass of NSObject, and isn't a subclass of an @objc class:
import Foundation
@objc protocol P {}
class C: P {}
Fixes #66

Correct a fact around @objc protocol adoption

---

.gitattributes
Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
Sources/TSPL/TSPL.docc/ReferenceManual/Attributes.md
Sources/TSPL/TSPL.docc/ReferenceManual/Declarations.md
Sources/TSPL/TSPL.docc/TSPL.md

Various minor changes:
- Fix a heading
- Disable the automatic "Overview" heading
- Fix formatting of term-definition lists
- Set a Git attribute for markdown files

Minor fixes

---

CONTRIBUTING.md

Now that we're almost ready to publish TSPL using DocC, we want to get ready for writing work in this Git repository besides DocC adoption.
Fixes rdar://96314288&96317008

Add workflow guidance for more substantive writing work

---

Sources/TSPL/TSPL.docc/ReferenceManual/LexicalStructure.md

This markup is the only way to create a code-voice backtick in markdown, even though it creates a warning due to DocC's meaning of double backticks to delimit code voice.  See also that known issue: <https://github.com/apple/swift-book/issues/71> & <https://github.com/apple/swift-markdown/issues/93>
The current markup for the 'code' and 'x' example in Lexical structure does render the backticks, but the backticks are in plain font instead of code voice, which isn't correct.
Fixes rdar://102988329

Fix markup for backtick in code voice

---

Sources/TSPL/TSPL.docc/LanguageGuide/Concurrency.md

Typo: lets -> let (subject/verb agreement)

---

Sources/TSPL/TSPL.docc/ReferenceManual/Attributes.md

This probably got overlooked by the searches when fixing https://github.com/apple/swift-book/pull/53 because it's a one-space indentation.  It wasn't a leftover from the Swift 1 era of intentional three-space indentations — this was just a markup error in source that didn't cause issues under the legacy RST publication pipeline because that pipeline reindented everything anyhow.
Fixes rdar://103197773

Fix incorrect (one-space) indentation.

---

Sources/TSPL/TSPL.docc/LanguageGuide/CollectionTypes.md
Sources/TSPL/TSPL.docc/LanguageGuide/Concurrency.md
Sources/TSPL/TSPL.docc/LanguageGuide/ControlFlow.md
Sources/TSPL/TSPL.docc/LanguageGuide/Enumerations.md
Sources/TSPL/TSPL.docc/LanguageGuide/StringsAndCharacters.md
Sources/TSPL/TSPL.docc/LanguageGuide/TheBasics.md
Sources/TSPL/TSPL.docc/ReferenceManual/Attributes.md
Sources/TSPL/TSPL.docc/ReferenceManual/Expressions.md
Sources/TSPL/TSPL.docc/ReferenceManual/LexicalStructure.md
Sources/TSPL/TSPL.docc/ReferenceManual/Statements.md
Sources/TSPL/TSPL.docc/ReferenceManual/Types.md

This was long during the RST export to markdown.  Found places to change by searching for "developer.apple.com/documentation" since all of the links are for standard library docs.  Verified that all API links have matching URLs by exporting a list of links from the current published version.
Fixes rdar://103197507

Restore code voice for links to API symbols

---

Sources/TSPL/TSPL.docc/LanguageGuide/CollectionTypes.md
Sources/TSPL/TSPL.docc/ReferenceManual/Attributes.md
Sources/TSPL/TSPL.docc/ReferenceManual/Declarations.md
Sources/TSPL/TSPL.docc/ReferenceManual/Patterns.md
Sources/TSPL/TSPL.docc/ReferenceManual/Statements.md
Sources/TSPL/TSPL.docc/ReferenceManual/Types.md

This matches the rest of the em-dashes in the book.  In most cases, because an em-dash is a clause boundary, it ends up at the end of the line with semantic line breaks.  The previous RST-based publication pipeline included a step to close up em-dashes, so these few exceptions didn't cause issues.
DocC doesn't close up em-dashes, and the current instruction from editorial is to set em-dashes open because the San Francisco font otherwise sets things too close together.  When setting this content in another font that doesn't have that issue, like Helvetica, we'd need to teach DocC to close up the em-dashes throughout.
Fixes rdar://102987894

Input em-dashes with space on both sides

---

Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md
Sources/TSPL/TSPL.docc/LanguageGuide/AdvancedOperators.md
Sources/TSPL/TSPL.docc/LanguageGuide/Concurrency.md
Sources/TSPL/TSPL.docc/LanguageGuide/Generics.md
Sources/TSPL/TSPL.docc/ReferenceManual/Declarations.md
Sources/TSPL/TSPL.docc/ReferenceManual/Statements.md

This got incorrectly converted from a numbered list to a bulleted list during the RST export to markdown.
Fixes rdar://102987273

Restore numbered lists

---

Sources/TSPL/TSPL.docc/TSPL.md
Sources/TSPL/TSPL.docc/header.html
bin/update-book-preview

As discussed in some of the docs workgroup meetings, it's useful for us to have a staging copy of the book.
Fixes https://github.com/apple/swift-book/issues/34

Add custom header for staging copy and build script

---

Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
Sources/TSPL/TSPL.docc/LanguageGuide/ClassesAndStructures.md
Sources/TSPL/TSPL.docc/LanguageGuide/NestedTypes.md
Sources/TSPL/TSPL.docc/LanguageGuide/Properties.md
Sources/TSPL/TSPL.docc/ReferenceManual/Statements.md
Sources/TSPL/TSPL.docc/ReferenceManual/Types.md

Fixes rdar://102988487
Fixes rdar://102988514
Fixes rdar://102995541
Fixes rdar://103188927

Adjust abstracts

---

Sources/TSPL/TSPL.docc/Info.plist
Sources/TSPL/TSPL.docc/LanguageGuide/Concurrency.md

Did a quick check, and it looks like these were the only code listings missing their syntax highlighting.  Before:
```% cmark --to xml **.md | grep --only-matching '<code_block[^>]*>' | sort -u
<code_block info="swift" xml:space="preserve">
<code_block xml:space="preserve">
```
After:
```
% cmark --to xml **.md | grep --only-matching '<code_block[^>]*>' | sort -u
<code_block info="swift" xml:space="preserve">
```
Fixes rdar://103217537

Specify code listings are in Swift

---

Sources/TSPL/TSPL.docc/RevisionHistory/RevisionHistory.md

We exported TSPL from RST to markdown after a beta of Swift 5.7 shipped, so the revision history at the time of export reflected the date when a prerelease version of TSPL shipped alongside that beta.  TSPL was published for Swift 5.7 FCS using the legacy RST version, where this date was updated after the markdown export.  This commit reflects the same change here, in the markdown version.

Correct the date for Swift 5.7 to FCS.

---

Sources/TSPL/TSPL.docc/LanguageGuide/StringsAndCharacters.md

Hello, I'm Bomi and learning a swift.
While studying, I found a sentence that would be better to modify so I suggest it.
I think the comma should be removed from this sentence so the conjunctions are not separated from each other.
Because `Either...or` is a correlative pair of conjunction.
I couldn't seen using commas in sentences of this chapter include correlative conjunction. I guess it would be better to change it for the uniformity.
Please review, Thanks! 💙

remove comma for correlative conjunction

---

Sources/TSPL/TSPL.docc/ReferenceManual/Declarations.md

When reviewing a PR (https://github.com/apple/swift/pull/62235) to improve the API reference for `Never` I noticed that TSPL doesn't link to the reference for that type anywhere.

Link to the API reference for Never

---

README.md

In the future, as part of formalizing the contribution process, we might end up with a separate forum category for these pitches — for now, they've been happening in the Swift Documentation category.

Match forum link in README and CONTRIBUTING

---

.git-blame-ignore-revs
.git_ignored_revs

For comparison, here are links to the tour's blame view with and without this setting.
Without: https://github.com/apple/swift-book/blame/main/TSPL.docc/GuidedTour/GuidedTour.md
With: https://github.com/amartini51/swift-book/blame/ignored_revs/Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md
Without this setting, almost half of the lines of the tour are attributed to commit 96f092540, the RST-to-markdown conversion.  With it, we get much more useful blame information:
```
% git blame GuidedTour.md | cut -d' ' -f 1 | sort | uniq -c | sort -n | tail
8 a79e857ab
10 c3e2f1463
10 dfde955ed
10 fe966592c
11 41be57f94
13 ee49b93bc
15 cee94fdde
30 940f17d35
174 8e84be0fc
1770 96f092540
% git blame --ignore-revs-file .git-blame-ignore-revs GuidedTour.md | cut -d' ' -f 1 | sort | uniq -c | sort -n | …
```

Ignore RST-to-markdown commit when blaming

---

README.md
TSPL.docc/header-staging.html

There are several links to the previous url where the Swift book was published, this PR here just gets rid of the main offender in the README. i'm hesitant to touch the other links, so i'll just drop this search for posterity: https://github.com/search?q=repo%3Aapple%2Fswift-book%20https%3A%2F%2Fdocs.swift.org%2Fswift-book%2F&type=code
as per https://github.com/apple/swift-book/issues/72

Update URLs that now redirect

---

TSPL.docc/footer.html

Several people pointed out that they would like a site-specific toggle for light/dark mode for the book: https://forums.swift.org/t/light-mode-for-swift-5-8-docs/63364
This PR adds a toggle like the one in the footer on the main swift.org site. I manually expanded the SCSS to CSS to avoid adding a build-time dependency for it. 
I deployed a test/preview version here: https://krilnon.github.io/swift-book/documentation/the-swift-programming-language/

Add appearance selection input to the footer

---

TSPL.docc/LanguageGuide/CollectionTypes.md

This code listing incorrectly matched a regex during the open-source export.

Restore a musical genre name in an example

---

TSPL.docc/LanguageGuide/Enumerations.md

This PR fixes a tiny text mistake in the sentence that you can find in the section [Associated Values](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/enumerations/#Associated-Values) of the chapter "Enumerations"
> If all of the associated values for an enumeration case are extracted as constants, or if all are extracted as variables, you can place a single `var` or `let` annotation before the case name, for brevity:
This PR swaps `var` and `let` annotation places in the sentence above.
Fixes https://github.com/apple/swift-book/issues/124

Match the prose order in code voice

---

TSPL.docc/GuidedTour/GuidedTour.md
TSPL.docc/LanguageGuide/StringsAndCharacters.md
TSPL.docc/ReferenceManual/Expressions.md

A bug in the legacy publication pipeline used to make this code listing render without the indentation, preventing us from using it.  That's no longer the case under DocC, so let's put back the richer example.
Fixes rdar://34530402

Show multiline string with indentation in the tour

---

TSPL.docc/RevisionHistory/RevisionHistory.md

I know that Swift 5.8 release date is Mar 30. But wrong date is displayed to swift-book revision history.
Please check this!
Thank you.

Fix release date error

---

TSPL.docc/LanguageGuide/Inheritance.md

This PR inserts a sentence that explains an extra link about `extension` in the section [Preventing Overrides](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/inheritance#Preventing-Overrides) of the chapter "Inheritance".
"Extension" is mentioned here for the first time. Therefore, it is appropriate to attach a link to it.
To be honest, it is not the first time. You might already find some examples in the Swift Tour, and the chapter "The Basics".
Nonetheless, this time it is mentioned without the link in advance of the chapter "Extensions".
As such, it would be better to have a link.

Add a forward reference about extensions

---

TSPL.docc/GuidedTour/GuidedTour.md
TSPL.docc/LanguageGuide/ClassesAndStructures.md
TSPL.docc/LanguageGuide/ControlFlow.md
TSPL.docc/ReferenceManual/Declarations.md
TSPL.docc/ReferenceManual/Expressions.md
TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md

Added a brief example of this syntax in the tour.
Added examples of this syntax alongside the existing `if` and `switch` statements in the guide.  I opted to explain it inline, rather than adding a new "If/Switch Expressions" section, because I think that will age better.  Today, this syntax is salient because it's new, but after a few years it will just be part of the language — and in the latter context, integrating it gives a better learning path.
Added a new "Conditional Expressions" section to the reference, which leans heavily on the existing "Conditional Statements" section but calls out the differences in behavior and requirements, and which describes the formal grammar of `conditional-expression`.
Fixes: rdar://104936324

Add discussion of 'if' and 'switch' expressions [SE-0380]

---

TSPL.docc/LanguageGuide/OptionalChaining.md

Because we're reusing the property names, we can use the shorter form as described in The Basics.

Use the short syntax to unwrap optional properties

---

TSPL.docc/ReferenceManual/Attributes.md

Fixed two locations where `buildPartialBlock(accumulated:next:)` was incorrectly referred to as `buildPartialBlock(second:)`.
_Note: I did make sure that neither was actually an incorrectly-named reference to `buildEither(second:)`._

Fix incorrect parameter names for buildPartialBlock(accumulated:next:)

---

TSPL.docc/LanguageGuide/AccessControl.md

The `open` access control level was missing from the Access Control Syntax section.

Add missing `open` access control level examples

---

TSPL.docc/LanguageGuide/AdvancedOperators.md

This was an oversight when updating the book's art program.

Fix prose that refers to parts of a figure by color

---

TSPL.docc/ReferenceManual/Expressions.md
TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md

Reviewed by @hamishknight in the issue's discussion.  This looks like it was just a copy/paste error.
Fixes: https://github.com/apple/swift-book/issues/145

Remove an infinite loop in the grammar

---

TSPL.docc/LanguageGuide/Macros.md

`OptionSet` was briefly included in the version of the Swift standard library that shipped with beta 1:
https://github.com/apple/swift/blob/release/5.9-20230510/stdlib/public/core/Macros.swift#L93
However, it has since been reverted:
https://github.com/apple/swift/pull/66403 (merged into 'main')
https://github.com/apple/swift/pull/66404 (cherry pick to 5.9 release branch)
We should watch for it to be approved in the Swift Evolution process, and then re-add the link (assuming it gets approved):
https://forums.swift.org/t/63547
https://github.com/apple/swift-evolution/pull/1968
Fixes: rdar://111109664

Remove reference to OptionSet being in the stdlib

---

TSPL.docc/ReferenceManual/Expressions.md
TSPL.docc/ReferenceManual/LexicalStructure.md

This change matches an [upstream change](https://github.com/apple/swift/pull/66500) in the publication pipeline that will start including the `()` at the end of macro's names.  TSPL started linking to the macros that replace what used to be special literals in commit f2828dd507eeb1e1b733ed24897cd3d838598a1c, which is on 'main' but isn't yet included in the published content.  So if the publication pipeline updates before this PR is merged, that's also ok — the links that would break aren't there yet.
Fixes: rdar://112501547

Include trailing () in macro URLs.

---

TSPL.docc/LanguageGuide/OpaqueTypes.md

Fixes rdar://112801273 (Type where identify should be identity)

Fix misspelling in Opaque Types chapter

---

TSPL.docc/GuidedTour/GuidedTour.md

Fix unused result warning for `defer` example in GuidedTour.md for Guided Tour Section
Fixes: https://github.com/apple/swift-book/issues/157

Fix unused result warning for `defer` example

---

README.md

Any wording review comments are welcomed.
https://forums.swift.org/t/unable-to-build-swift-book-via-docc/66342
Fixes: https://github.com/apple/swift-book/issues/163

Update README for guiding docc location

---

TSPL.docc/ReferenceManual/AboutTheLanguageReference.md
TSPL.docc/ReferenceManual/Attributes.md
TSPL.docc/ReferenceManual/Declarations.md
TSPL.docc/ReferenceManual/Expressions.md
TSPL.docc/ReferenceManual/GenericParametersAndArguments.md
TSPL.docc/ReferenceManual/LexicalStructure.md
TSPL.docc/ReferenceManual/Patterns.md
TSPL.docc/ReferenceManual/Statements.md
TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md
TSPL.docc/ReferenceManual/Types.md

The formatting of the grammar changes as follows:
- Delete single blank lines.
- Collapse multiple blank lines into a single blank line.
- Add a hard break (` \`) except before blank or at the end.
Fixes: rdar://112146913
Fixes: https://github.com/apple/swift-book/issues/54

Switch the grammar to use hard breaks.

---

TSPL.docc/LanguageGuide/Macros.md
TSPL.docc/ReferenceManual/Expressions.md
bin/preflight

Identified broken links by running the commands that I added to the `preflight` script.  Confirmed there aren't any broken links remaining.
Someone more familiar with XPath might be able to rewrite that bit to print only the attribute name, removing the `cut` and `sed` post-processing steps.  When I changed the query to `string(//link/@destination)`, which I would have expected to do that, I get only the first link's destination instead of all of them..

Fix broken and old links

---

TSPL.docc/ReferenceManual/Attributes.md

The `buildPartialBlock(first:)` and `buildPartialBlock(accumulated:next:)` methods are described by the "Result-Building Methods" subsection of `@resultBuilder`, but there is no corresponding detail provided in the "Result Transformations" subsection. This adds the appropriate description, including example code which demonstrates the intended use case.
(The point is admittedly partly moot in Swift 5.9, given that it became possible to write a result builder that has `func buildBlock<each D: Drawable>(_ components: repeat each D) -> some Drawable`, but the `buildPartialBlock()` methods may still be a better fit for some use cases. Even if this were not the case, they still exist and should be fully documented.)

Describe how result builders interact with "build partial block"

---

TSPL.docc/LanguageGuide/ErrorHandling.md

Because the discussion of `defer` is divided between the error-handling and non-error-handling use cases, it's helpful to have cross references that go in both directions.  The section in Control Flow already links here at the end.

Add a back-reference for 'defer' as used outside error handling

---

TSPL.docc/ReferenceManual/Expressions.md

Fixes: https://github.com/apple/swift-book/issues/179

Fix grammar of infix expressions, to allow 'await'.

---

TSPL.docc/LanguageGuide/Macros.md

The term `SwiftSystem` appears in Macros section, but I don't know what it references.
I'm not entirely sure, but from the context, it might be referring to `SwiftSyntax`.
Based on this reasoning, I replaced `SwiftSystem` with `SwiftSyntax`.

Replace 'SwiftSystem' with 'SwiftSyntax' in Macros section.

---

TSPL.docc/LanguageGuide/Macros.md

Fixed a test code referencing a non-existent type `FourCC`. Changed it to `FourCharacterCode`.

The type `FourCC` is incorrectly used in the test code of Macros.

---

TSPL.docc/LanguageGuide/Macros.md

In Macro section, a function is referenced as `FourCharacterCode`, but its actual definition is `fourCharacterCode`.
Correcting the reference.

Fix the first letter of a referencing function name in Macros.

---

Style.md
TSPL.docc/LanguageGuide/TheBasics.md
TSPL.docc/ReferenceManual/Declarations.md

This pull request adds an example of defining a constant without assigning a value to it immediately, and then setting a value based on a condition. 
Fixes: https://github.com/apple/swift-book/issues/139
Fixes: rdar://114058607
- I'm just getting started and learning — I _think_ I got the `swifttest` syntax right? 
/cc @amartini51. How does that look? Are small contributions like this one useful at all? 🙃

Example of constant with deferred assignment

---

Style.md
TSPL.docc/LanguageGuide/AdvancedOperators.md
TSPL.docc/LanguageGuide/ClassesAndStructures.md
TSPL.docc/LanguageGuide/Generics.md
TSPL.docc/LanguageGuide/Protocols.md
TSPL.docc/LanguageGuide/StringsAndCharacters.md
TSPL.docc/ReferenceManual/Declarations.md
TSPL.docc/ReferenceManual/Statements.md

In context, there's only one "standard library" for Swift, so it's unlikely someone would misread that to meaning anything other than "the Swift standard library".  But it's still worthwhile to be consistent.
Per discussion with Chuck in another edit, circa May 2023.
Fixes: rdar://110033045

Consistently use "the Swift standard library"

---

TSPL.docc/ReferenceManual/Declarations.md
TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md

This production used to be part of the old approach to enum grammar — see commit 0f8a59f46999c7815fbf932743368e6146e2cb0d.  Brian, can you think of any reasons we might want to keep the old approach around?  (You committed it, but most likely you and I wrote it together.)
Fixes: https://github.com/apple/swift-book/issues/187

Remove unreachable 'declarations' grammar production

---

TSPL.docc/GuidedTour/GuidedTour.md

See commit b7cdc2ffa38ad1c5b9278e68a071cdccf8fa1946 which changed this throughout the Concurrency chapter.  The new content in the tour wasn't on the branch where we made that  fix.

Match a variable name change in the tour

---

TSPL.docc/ReferenceManual/Expressions.md
TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md

The old grammar didn't allow things like f(&x.y) which are legal in Swift.  The new grammar allows a bunch of stuff -- literals, closures, and conditional expressions -- but that's a better problem to have.
See also #194, where we're discussing a more specific fix.
Fixes: https://github.com/apple/swift-book/issues/193 (partially)

Fix in-out grammar underproduction

---

TSPL.docc/ReferenceManual/Declarations.md
TSPL.docc/ReferenceManual/Types.md

This documents the `borrowing` and `consuming` parameter modifiers introduced by [SE-0377][].
These are comparatively niche, so I'm only documenting them in the "Reference Manual" section for now.
I've structured this by:
* Creating a new "Parameter Modifiers" section with a brief description of the modifiers concept,
* Moving the old "In-Out Parameters" description under it, and
* Adding a new subsection on Borrowing and Consuming Parameters.
I've also adjusted the "In-Out Parameters" introduction so it starts with a code example showing the `inout` syntax and usage.
[SE-0377]: https://github.com/apple/swift-evolution/blob/main/proposals/0377-parameter-ownership-modifiers.md
Fixes: rdar://116031853

SE-0377: Document the `borrowing` and `consuming` parameter modifiers

---

TSPL.docc/LanguageGuide/Concurrency.md

This typo came from ac5ce6a7b5337521fa4b3715ffb335511cd3103e.

Fix typo in description of convertFarenheitToCelsius()

---

TSPL.docc/LanguageGuide/TheBasics.md

In the sentence contained between lines 1612 and 1615 of "The Basics", a grammatical error before the word "programmer" can be found:
> When nil represents an unrecoverable failure, such **_a_** programmer error or corrupted state, you can access the underlying value by adding an exclamation mark (!) to the end of the optional’s name.
By adding the word "as" before "a", the sentence becomes grammatically correct:
> When nil represents an unrecoverable failure, such **_as a_** programmer error or corrupted state, you can access the underlying value by adding an exclamation mark (!) to the end of the optional’s name.

Fix grammar error in The Basics

---

TSPL.docc/LanguageGuide/Concurrency.md

The code listing changed in c554b62bcc3162a4df2fd61ffc41634e16c6b733 but the old example got left behind in the prose and swifttest block.
Fixes: https://github.com/apple/swift-book/issues/224

Match code listing for nonsendable example

---

TSPL.docc/ReferenceManual/Attributes.md
TSPL.docc/ReferenceManual/Statements.md
TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md

Add visionOS extension to platform lists

---

TSPL.docc/GuidedTour/GuidedTour.md

When changing the condition to `m <  0`, it is false from the start, not true from the start.

GuidedTour: Fixed while and repeat-while experiment description

---

TSPL.docc/Info.plist

This removes a handful of property list keys from the Info.plist file in the documentation catalog that are not used by DocC.
These property list keys have no effect on the documentation build and only distract from the keys that _are_ used by DocC.

Remove Info.plist keys that are never used by DocC

---

TSPL.docc/LanguageGuide/Concurrency.md

Fixed typo (convertFarenheitToCelsius -> convertFahrenheitToCelsius)
As far as I confirmed, there is no duplicated PR.

Fix spelling of Fahrenheit in example method

---

TSPL.docc/LanguageGuide/NestedTypes.md
TSPL.docc/LanguageGuide/Protocols.md
TSPL.docc/ReferenceManual/Declarations.md

Didn't add an example to the tour, because it doesn't show nested types — we can revise that separately.
Fixes: rdar://117101695

Show example of nested protocols [SE-0404]

---

TSPL.docc/ReferenceManual/Expressions.md
TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md

The grammar around subscripts and C-style for loops used to use this production, but the former now uses function-argument-list (1) and the latter was removed from the Swift language (2).
(1) 27491635d9cda7e71208643f16b758302a5016c7
(2) aaff06cb0c83481adc9e6cd0be6fef15542215d7
Fixes: https://github.com/apple/swift-book/issues/274

Remove disused grammar production

---

TSPL.docc/LanguageGuide/Concurrency.md

I'm reading through the concurrency section, and I stumbled across a code snippet that does not compile. It has two errors:
- It is missing a generic parameter
- It relies on an async override for Result that may one day exist, but does not today
Further I think it is slightly confusing to mix the use of await and throws, when the section is fairly clear about making the distinction between the two.
My solution fixes the syntax, and slightly changes the method being used to remove even a suggestion of concurrency usage.

Fix code in Result example

---

TSPL.docc/LanguageGuide/Concurrency.md

The code listing tried to access the `isCancelled`  property without specifying `Task.isCancelled`.  That would work in the scope of a task, because there's an instance property with that name.  But it doesn't work in the context of calling `addTaskUnlessCancelled(priority:operation:)` to adding a child task to a task group — in that case, you need to use the type property.

Fixes task cancellation sample code

---

TSPL.docc/LanguageGuide/OpaqueTypes.md

The third  code block in this [section of the docs](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/opaquetypes#The-Problem-That-Opaque-Types-Solve) has the following declaration.
`let joinedTriangles = JoinedShape(top: smallTriangle, bottom: flippedTriangle)`
In the paragraph above the declaration, the docs mentions the following.
>  results in types like `JoinedShape<FlippedShape<Triangle>, Triangle>`
However, the actual dynamic type is `JoinedShape<Triangle, FlippedShape<Triangle>>`. This PR suggests rephrasing the sentence to match the actual dynamic type.

Fix prose to match code listing for opaque type

---

TSPL.docc/ReferenceManual/Attributes.md

Adds a missing closing bracket to Attributes in the reference manual

Add missing parenthesis in reference for macro names

---

.github/PULL_REQUEST_TEMPLATE.md

Most of the pull requests so far have used this ordering, and I occasionally have to look back at Git history to follow precedent, so it's worth just writing this down explicitly.

Standardize ordering of pieces in PR template

---

TSPL.docc/LanguageGuide/AccessControl.md
TSPL.docc/ReferenceManual/Attributes.md

This got incorrectly changed as part of normalizing indentation in code listings to 4 spaces.
Reviewed the changes in 28a4aafbf9dd153fe96473e9b08c885a32cd7fc1 and I don't see any remaining indentation problems that weren't already fixed by a130dfcd8ad50390dc2ee510059cfb0a0abf78eb or fixed by this PR.

Align comments vertically

---

TSPL.docc/LanguageGuide/OpaqueTypes.md

In the content, "boxed protocol types" is used, but it's not used in the title.
I'm not sure if it's intended or not, but it looks missing "Protocol".

Add missing "Protocol" to the title

---

TSPL.docc/ReferenceManual/LexicalStructure.md

Adds consuming and borrowing to the list of keywords
Fixes: [#300](https://github.com/apple/swift-book/issues/300)

Add 'borrowing' and 'consuming' to list of keywords

---

TSPL.docc/ReferenceManual/Patterns.md

Fixes: https://github.com/apple/swift-book/issues/304

Name the ~= operator when introducing it

---

TSPL.docc/LanguageGuide/ErrorHandling.md
TSPL.docc/ReferenceManual/Declarations.md
TSPL.docc/ReferenceManual/Expressions.md
TSPL.docc/ReferenceManual/Statements.md
TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md
TSPL.docc/ReferenceManual/Types.md

Update error handling for typed throws [SE-0413]

---

TSPL.docc/GuidedTour/Compatibility.md
TSPL.docc/LanguageGuide/ControlFlow.md
TSPL.docc/ReferenceManual/Statements.md
TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md

Add missing visionOS operating-system.
It's defined here:
https://github.com/apple/swift/blob/main/include/swift/AST/PlatformKinds.def#L28
rdar://129595552
---
Also, not addressed here, but it looks like there is an inconsistency between the book and the language regarding:
- swift-book/TSPL.docc/ReferenceManual/Statements.md line 1256 says `Linux`
- swift-book/TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md line 701 says `Linux`
- swift/include/swift/AST/PlatformKinds.def line 37 says `OpenBSD`
It could be worth investigating the disparity.

Add visionOS operating-system

---

TSPL.docc/LanguageGuide/Macros.md

Code
```swift
@attached(member, names: named(RawValue), named(rawValue),
named(`init`), arbitrary)
```
Prose
```
the `@attached(member)` macro includes arguments after the `named:` label
```
In the code the label is referred to as "`names`", but the prose refers to it as "`named`". This PR suggests a doc fix that uses the correct label ("`names`") in the prose.

Fix typo in macro name

---

TSPL.docc/ReferenceManual/Declarations.md

Breaking this up into bullets and rewording it should make it easier to read.

Reword extensions in access control

---

TSPL.docc/ReferenceManual/Attributes.md

A common misconception that people have about `buildLimitedAvailability` is that it enables the following syntax in result builders:
```swift
@DrawingBuilder var x: Drawable {
if #available(macOS 99, *) {
FutureText("Inside.future")
} else {
Text("Inside.present")
}
}
```
and would implement `buildLimitedAvailability` as follows:
```swift
static func buildLimitedAvailability(component: some Drawable) -> some Drawable {
component
}
```
However, the above code will still result in a crash in an earlier OS where `FutureText` is not available. 
**This change calls out the importance and need to perform type erasure in `buildLimitedAvailability`.**

Emphasize type erasure in  buildLimitedAvailability

---

CODE_OF_CONDUCT.md

Remove this repo-local copy, to follow the swiftlang org-wide policy instead of individual repo files. Having this file present means the repo is opt-ing out of the org wide policy, which is not the case.

Remove code of conduct

---

TSPL.docc/ReferenceManual/Attributes.md

Add a missing "or" to the documentation of result builders.

Fix minor grammatical issue in Attributes.md

---

TSPL.docc/LanguageGuide/Initialization.md

This pull request addresses a terminology issue in the "[Overriding a Failable Initializer](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/initialization/#Overriding-a-Failable-Initializer)" section of the Swift Language Guide. The explanation incorrectly referred to `"[Untitled]"` from the example as a "string constant," which is not accurate. In Swift, `"[Untitled]"` is a string literal, not a constant.
```swift
super.init(name: "[Untitled]")!
```

Fix terminology for string literal in example explanation

---

TSPL.docc/LanguageGuide/Concurrency.md
TSPL.docc/LanguageGuide/Macros.md
TSPL.docc/ReferenceManual/Attributes.md
TSPL.docc/ReferenceManual/Declarations.md
TSPL.docc/ReferenceManual/LexicalStructure.md
TSPL.docc/ReferenceManual/Statements.md
TSPL.docc/ReferenceManual/Types.md
TSPL.docc/header-staging.html
bin/preflight

Fix some incorrect and outdated URLs.  Switch to HTTPS in a few places.  Improve detection of broken links in the preflight script.
Co-authored-by: Marc Liyanage <liyanage@apple.com>
Co-authored-by: Apollo Zhu <zhuzhiyu@apple.com>

Fix some broken links

---

TSPL.docc/LanguageGuide/Concurrency.md
TSPL.docc/LanguageGuide/Macros.md
TSPL.docc/ReferenceManual/Expressions.md

Because the `Info.plist` file specifies Swift as the default language via the `CDDefaultCodeListingLanguage` key, code listings with an unspecified language should still render correctly.  However, it's still good to be explicit and makes the markdown files more usable by other toolchains.
Used the following script to find code listings that were missing an explicit language, and to verify that none remain after this change:
```
echo "Not specified as Swift"
cmark --to xml TSPL.docc/*/*.md |
xpath -q -n -e '//code_block[not(@info="swift")]'
echo "Languages used"
cmark --to xml TSPL.docc/*/*.md |
xpath -q -n -e '//code_block/@info' |
sort -u
```

Specify code listings are Swift

---

bin/publish-book
bin/redirects/documentation/index.html
bin/redirects/index.html

Without this redirect, the server generates a directory listing for <https://docs.swift.org/swift-book/documentation/> and you have to click through to the actual content.
This page uses a reduced version of the existing redirect page, with the majority of the JavaScript removed.  Because we never hosted any pre-DocC content at this URL, there's no reason to inspect the fragment and do a more specific redirect.  There aren't any old URLs that point here for us to avoid breaking.
Fixes: rdar://137038334

Add a redirect at the top level

---

TSPL.docc/LanguageGuide/CollectionTypes.md

This pull request resolves an inconsistency in the "**Creating an Empty Array**" section of the Swift Language Guide under "**Collection Types**."
- Updated the example code by replacing `var someInts: [Int] = []` with `var someInts = [Int]()` to accurately demonstrate type inference, aligning with the accompanying explanatory text.
The previous example did not demonstrate type inference, as the type `[Int]` was explicitly declared using `: [Int]`. However, the accompanying text states:  
> "Note that the type of the `someInts` variable is **inferred** to be `[Int]` from the type of the initializer."  
This was misleading because type inference did not occur in the provided example. The updated example clarifies the explanation and ensures consistency across the guide, aligning with …

Fix type inference example in "Creating an Empty Array"

---

TSPL.docc/LanguageGuide/Concurrency.md

The old example actually makes an atomic update to the array of temperatures because it uses `map`.  Updating them in a `for` loop makes it more obvious that some temperatures will be Fahrenheit and some Celsius when the program's in the middle of the loop.
Fixes: rdar://139633262

Improve concurrency example of transient invalid states

---

TSPL.docc/Info.plist
bin/redirects/redirect.swift

Confirmed there aren't any remaining by running:
```sh
git grep -I $'\t'
git grep -I ' $'
```

Remove trailing spaces and all hard tabs

---

TSPL.docc/LanguageGuide/ErrorHandling.md

The Swift documentation contains an incorrect function declaration in the Error Handling section:
The throws modifier should be before { and not after ->.
Current (incorrect) code:
```
func someThrowingFunction() -> throws 
func someThrowingFunction() -> throws(any Error)
```
Fix:
```
func someThrowingFunction() throws 
func someThrowingFunction() throws(any Error)
```
Documentation Link:
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/errorhandling#Specifying-the-Error-Type
Issue Link:
https://github.com/swiftlang/swift-book/issues/360
Similar Pull-Request:
https://github.com/swiftlang/swift-book/pull/358

Fix incorrect throws syntax in error handling documentation

---

TSPL.docc/ReferenceManual/Statements.md

There have been requests on several occasions to add an architecture or OS that isn't officially supported, based on the fact that the compiler supports it.  This wording should make it a little clearer why not everything that "works" is listed in TSPL.

Clarify in-source comment about platforms

---

bin/publish-book
bin/update-book-preview

TSPL hasn't needed DocC to build built from source for a while now.  Relying on Xcode for `docc` simplifies and speeds up the build process.

Use the DocC from Xcode

---

TSPL.docc/LanguageGuide/Generics.md
TSPL.docc/LanguageGuide/OpaqueTypes.md
TSPL.docc/ReferenceManual/Types.md

Add discussion of 'some' on parameter types [SE-0341]

---

TSPL.docc/LanguageGuide/ControlFlow.md
TSPL.docc/LanguageGuide/Enumerations.md

This syntax was previously shown only in the reference, under [Optional Patterns](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/patterns#Optional-Pattern).  I've added a new section to the Control Flow chapter to discuss this — pattern-matching against tuples because that's the only suitable data type available at this point in the book.  I've added forward and backward cross-references to the section about enumerations that have associated values, because this syntax is the way you extract that associated value.
Fixes: rdar://145579866

Show if-case and for-case in the guide

---

TSPL.docc/LanguageGuide/TheBasics.md

Define what "safe"means

---

TSPL.docc/LanguageGuide/Concurrency.md
TSPL.docc/LanguageGuide/Protocols.md

This syntax does not exist yet, and if you write `~Sendable`, you'll get a compiler error that a conformance to `Sendable` cannot be suppressed. It's a good idea but it is neither pitched nor implemented.

Remove the mention of `~Sendable` from the concurrency chapter.

---

TSPL.docc/LanguageGuide/Initialization.md
TSPL.docc/LanguageGuide/Properties.md

The Language Guide expects that property observers will be triggered during initialization in some circumstances, but they categorically aren't triggered. I ran into this while building some example code on property observers and, without being too much of a language lawyer, I'd like to suggest a minor clarification.
The current note on property observer behavior during initialization [1] reads:
> Note: The `willSet` and `didSet` observers of superclass properties
> are called when a property is set in a subclass initializer,
> after the superclass initializer has been called.
> They aren't called while a class is setting its own properties,
> before the superclass initializer has been called.
The first sentence on superclass behavior is true, but the final sentence on same-class behavior …

Clarify property observer behavior during initialization

---

TSPL.docc/ReferenceManual/Attributes.md

This PR fixes a documentation bug stating that the `names:` argument is required for `@attached` macros with the `accessor` role. In reality, this argument is not required for accessor macros.
Fixes: https://github.com/apple/swift-book/issues/374

Fix list of macro roles that need "names:" argument
